spring:
  datasource:
    url: jdbc:mysql://localhost:3306/annualPermit
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    displayOperationId: true
    displayRequestDuration: true

number-of:
  annual:
    permit:
      day:
        for:
          new:
            employee: 5
          between:
            one-and-five-equal: 15
            five-and-ten-equal: 18
          greater-ten: 24

